export const db = "main-stackflow"
export const questionsCollection = "questions"
export const answersCollection = "answers"
export const commentsCollection = "comments"
export const votesCollection = "votes"
export const questionAttachmentBucket = "question-attachments"